# Header
menu:
  Home: ../
  Archives: ../blog/archives
rss: ../blog/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-51701738-1    
favicon: ../blog/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
